### ISSUE TITLE
Now "0.0.0.0" should not be in non-acceptable network list in Confifguring BGP

### ISSUE THREAD

**Issue by Itohtak** [ibm-cloud-docs/direct-link#157]
Could you access  that "0.0.0.0" should be contained in non-acceptable network list in BGP configuration? The technical support told us that now 0.0.0.0 can be accepted.
Such as;
Note: The following networks are filtered out and cannot be accepted: 0.0.0.0, 10.0.0.0/14, 10.198.0.0/15, 10.200.0.0/14, 169.254.0.0/16, 224.0.0.0/4.
=> Note: The following networks are filtered out and cannot be accepted: 10.0.0.0/14, 10.198.0.0/15, 10.200.0.0/14, 169.254.0.0/16, 224.0.0.0/4.

Thanks.

**Comment by austinmama** [comment]
Updated on the staging and production server.  Thank you for your feedback!
