### ISSUE TITLE
Global Routing option of 1Gbps is the same price regardless of location.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/direct-link#163]
Hello,

The 1Gbps Global Routing option is the same price ($2,999) regardless of location. At other speeds, prices vary from place to place.
Is it correct?

https://cloud.ibm.com/docs/direct-link?topic=direct-link-pricing-for-ibm-cloud-direct-link#pricing-for-global-routing-add-on

Thanks,

**Comment by austinmama** [comment]
@ytama  Thank you for leaving this feedback.  I checked with Direct Link offering management and revised the table for global routing here: [https://cloud.ibm.com/docs/direct-link?topic=direct-link-pricing-for-ibm-cloud-direct-link#pricing-for-global-routing-add-on](url)

We appreciate that you took the time to question this inaccurate pricing & leave a comment.
