### ISSUE TITLE
Direct Link ECX order: Account ID ? 

### ISSUE THREAD

**Issue by saka0315** [ibm-cloud-docs/direct-link#168]
Hello,
The Classic Softlayer Account ID needed for ECX order
means the client's unique account ID which's initially created to start 
using IBM Cloud regardless of direct link.
So It should be changed not to confuse DirecLink clients.

6.On the Connection Details page, enter the connection information. For Account ID, enter the Classic Softlayer Account ID (for example, 114340xxx) that was generated when you provisioned your direct link. This key can be found on the Direct Link details page.

https://cloud.ibm.com/docs/direct-link?topic=direct-link-how-to-order-ibm-cloud-direct-link-exchange#provisioning-ibm-cloud-direct-link-exchange-for-equinix

**Comment by austinmama** [comment]
Thank you.  The documentation was updated previously.  Closing this issue.
