### ISSUE TITLE
yum install epel-release this command in cent OS doesnt work

### ISSUE THREAD

**Issue by rgentyala** [ibm-cloud-docs/direct-link#169]
Actually Yum may not be a command that work in either any IBM Cloud image whether redhat or Cent OS as we have our own repos to send these patches and if that is true we need to fix all our documentation referring to YUM command.

sudo apt install is another command that is working, however in this case epel-release is missing to download and install.

With WGET using this command: wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

I got to the repo in to /tmp folder but installing that may not be allowed. Please fix this and respond to me on my email or a way that can help me know when this is fixed.

**Comment by austinmama** [comment]
Direct Link 2.0 documentation does not include the **Yum** command.  Closing.
