### ISSUE TITLE
A broken link in Db2 Warehouse on Cloud document

### ISSUE THREAD

**Issue by yamasakk** [ibm-cloud-docs/direct-link#170]
Below link does not work:
https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-setting-up-access-to-your-classic-infrastructure-from-vpc#how-you-can-initiate-the-conversion

Above link in an IBM Cloud Document for Db2 Warehouse on Cloud:
https://cloud.ibm.com/docs/direct-link?topic=direct-link-overview-of-virtual-routing-and-forwarding-vrf-on-ibm-cloud#overview-of-virtual-routing-and-forwarding-vrf-on-ibm-cloud

**Comment by austinmama** [comment]
Fixed.  Thank you!
