### ISSUE TITLE
changes to process enabling VRF since 30 November 2023 not reflected here

### ISSUE THREAD

**Issue by gridhawk** [ibm-cloud-docs/direct-link#171]
By default, classic accounts that were established before 30 November 2023, are included in the IBM Cloud general routing table. Previously, if you wanted to convert a classic account to a VRF-style account, you were required to open a support case with IBM® Support. Beginning 30 November 2023, any new classic account or any existing classic account that is "empty" (for example, without any provisioned VLANs), will be automatically converted to a VRF-style account the next time that account initiates a private network connection. For more information, see FAQs about VRF account migration. https://cloud.ibm.com/docs/account?topic=account-vrf-faqs

**Comment by austinmama** [comment]
@gridhawk  Hi Sven.  Is this the right topic to add this information to?  https://cloud.ibm.com/docs/direct-link?topic=direct-link-configure-ibm-cloud-direct-link#more-about-using-vrf

**Comment by austinmama** [comment]
Updated: https://cloud.ibm.com/docs/direct-link?topic=direct-link-configure-ibm-cloud-direct-link#more-about-using-vrf
